### ISSUE TITLE
 piping-server-rust --enable-https panic

### ISSUE THREAD

**Issue by bhzhu203** [nwtgck/piping-server-rust#243]
/usr/bin/piping-server --http-port 8888 --enable-https --https-port 8889 --crt-path /home/dns.crt --key-path /home/dns.key
thread 'main' panicked at 'removal index (is 0) should be < len (is 0)', library/alloc/src/vec/mod.rs:1378:13
stack backtrace:
   0:     0x7f598af4ba20 - <unknown>
   1:     0x7f598af8171c - <unknown>
   2:     0x7f598af46d15 - <unknown>
   3:     0x7f598af4daeb - <unknown>
   4:     0x7f598af4d5c1 - <unknown>
   5:     0x7f598af4e1b4 - <unknown>
   6:     0x7f598af4dc97 - <unknown>
   7:     0x7f598af4bebc - <unknown>
   8:     0x7f598af4dbf9 - <unknown>
   9:     0x7f598ac4db11 - <unknown>
  10:     0x7f598ac4d916 - <unknown>
  11:     0x7f598ad7a3e4 - <unknown>
  12:     0x7f598ad7a5ee - <unknown>
  13:     0x7f598aca70d8 - <unknown>
  14:     0x7f598acb3938 - <unknown>
  15:     0x7f598aca1137 - <unknown>
  16:     0x7f598acd8788 - <unknown>
  17:     0x7f598acff1c8 - <unknown>
  18:     0x7f598acadb63 - <unknown>
  19:     0x7f598acd09e9 - <unknown>
  20:     0x7f598af4e710 - <unknown>
  21:     0x7f598acff312 - <unknown>
[root@data4 ~]# /usr/bin/piping-server --help
piping-server 0.10.2
Piping Server in Rust

**Comment by bhzhu203** [comment]
The latest version is the same

 /usr/bin/piping-server --http-port 8888 --enable-https --https-port 8889 --crt-path /home/dns.crt --key-path /home/dns.key
[2022-03-28T06:49:38Z INFO  piping_server] Piping Server (Rust) 0.12.1
thread 'main' panicked at 'removal index (is 0) should be < len (is 0)', src/util.rs:123:10
stack backtrace:
   0:     0x7ff7b5e9809c - <unknown>
   1:     0x7ff7b5ed123c - <unknown>
   2:     0x7ff7b5e91a28 - <unknown>
   3:     0x7ff7b5e9a547 - <unknown>
   4:     0x7ff7b5e9a20f - <unknown>
   5:     0x7ff7b5e9acaa - <unknown>
   6:     0x7ff7b5e9a997 - <unknown>
   7:     0x7ff7b5e98544 - <unknown>
   8:     0x7ff7b5e9a699 - <unknown>
   9:     0x7ff7b5ba7b83 - <unknown>
  10:     0x7ff7b5ba7962 - <unknown>
  11:     0x7ff7b5cc7e77 - <unknown>
  12:     0x7ff7b5cc8180 - <unknown>
  13:     0x7ff7b5becfcc - <unknown>
  14:     0x7ff7b5bb71a8 - <unknown>
  15:     0x7ff7b5bebdc7 - <unknown>
  16:     0x7ff7b5c35a44 - <unknown>
  17:     0x7ff7b5bbd963 - <unknown>
  18:     0x7ff7b5c221bd - <unknown>
  19:     0x7ff7b5e977f4 - <unknown>
  20:     0x7ff7b5c3d992 - <unknown>

**Comment by bhzhu203** [comment]
built with static option

cargo build --release --target=x86_64-unknown-linux-musl

**Comment by nwtgck** [comment]
Thank you so much for the report. I noticed just now... I'll see this.

**Comment by nwtgck** [comment]
Did you try to use a portable binary: <https://github.com/nwtgck/piping-server-rust/releases/download/v0.12.1/piping-server-x86_64-unknown-linux-musl.tar.gz>?


Could you try the following command to generate `ssl_certs/server.key` and `ssl_certs/server.crt`?

```bash
(mkdir ssl_certs && cd ssl_certs && openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365 -sha256 -nodes --subj '/CN=localhost/')
```

**Comment by bhzhu203** [comment]
There is no problem with the self signed certs. But panic  with normall https certs , such as  zerossl certs . 

acme.sh  --issue -d domain   --standalone

```
./piping-server-x86_64-unknown-linux-musl/piping-server --https-port 8888 --crt-path /root/.acme.sh/xxxxxxxxxx/fullchain.cer --key-path /root/.acme.sh/xxxxxxxxxx/xxxxxxxxxx.key  --enable-https
[2022-06-15T02:49:14Z INFO  piping_server] Piping Server (Rust) 0.12.1
thread 'main' panicked at 'removal index (is 0) should be < len (is 0)', src/util.rs:123:10
stack backtrace:
   0:           0x6f58ac - std::backtrace_rs::backtrace::libunwind::trace::h77e2ca07ef63e4d4
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:           0x6f58ac - std::backtrace_rs::backtrace::trace_unsynchronized::hee4866ffc0258806
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:           0x6f58ac - std::sys_common::backtrace::_print_fmt::h228418e02eb0f8fc
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:           0x6f58ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h855e38790874b97a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:           0x72e6cc - core::fmt::write::h42c44c4c71e808e0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:           0x6ef143 - std::io::Write::write_fmt::h42b4dd70169d991f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:           0x6f8222 - std::sys_common::backtrace::_print::h9931fc7c5b71fd53
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:           0x6f8222 - std::sys_common::backtrace::print::ha50ba850f23815df
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:           0x6f8222 - std::panicking::default_hook::{{closure}}::hecdd69c96d580ce5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:           0x6f7e05 - std::panicking::default_hook::h7928b9e2bcca33b5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:           0x6f8873 - std::panicking::rust_panic_with_hook::h165aa2fa5fe93a26
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:           0x6f8590 - std::panicking::begin_panic_handler::{{closure}}::h33ea6995ff6f26c6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:           0x6f5d54 - std::sys_common::backtrace::__rust_end_short_backtrace::h5e001056b3d239a9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:           0x6f82c9 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:           0x410311 - core::panicking::panic_fmt::h25f4bace64163d71
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:           0x410172 - alloc::vec::Vec<T,A>::remove::assert_failed::h7fcfe9e4e1409529
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/vec/mod.rs:1397:13
  16:           0x52b9e1 - piping_server::util::load_tls_config::h36defb802546805d
  17:           0x52bc46 - piping_server::util::hot_reload_tls_cfg::h2ff9686b2cba8270
  18:           0x44060e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h728fa4d7764166e9
  19:           0x476b48 - tokio::park::thread::CachedParkThread::block_on::h79212645e509f3d4
  20:           0x417847 - tokio::runtime::thread_pool::ThreadPool::block_on::ha7b4225a02e10fd2
  21:           0x486af8 - tokio::runtime::Runtime::block_on::h8a376a648c6771cd
  22:           0x496a49 - piping_server::main::h535998e8b858032d
  23:           0x479fd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfe403c2f668db5c3
  24:           0x486b8d - std::rt::lang_start::{{closure}}::hf5b5111d2f352d4e
  25:           0x6f4ff0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::heaf574743191e15b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  26:           0x6f4ff0 - std::panicking::try::do_call::h60c0c5ed566cfa08
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  27:           0x6f4ff0 - std::panicking::try::hdf3f2b36564f953d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  28:           0x6f4ff0 - std::panic::catch_unwind::hc3b6348826703723
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  29:           0x6f4ff0 - std::rt::lang_start_internal::{{closure}}::hf9c39ce91fc3ea64
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  30:           0x6f4ff0 - std::panicking::try::do_call::hb63d8c4b5823a9ea
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  31:           0x6f4ff0 - std::panicking::try::hfff1ffa733fc0b90
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  32:           0x6f4ff0 - std::panic::catch_unwind::hd0081cbdc19bd646
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  33:           0x6f4ff0 - std::rt::lang_start_internal::hc166cd9392444b47
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  34:           0x4a1162 - main
```

**Comment by nwtgck** [comment]
Thanks. 

I seems the format is not supported. I should try to use zerossl to get the format.

Could you try the following command? It is the original version of Piping Server in Node.js.

```
curl -L https://github.com/nwtgck/piping-server-pkg/releases/download/v1.12.3/piping-server-pkg-linuxstatic-x64.tar.gz | tar xzvf -
./piping-server-pkg-linuxstatic-x64/piping-server --https-port 8888 --crt-path /root/.acme.sh/xxxxxxxxxx/fullchain.cer --key-path /root/.acme.sh/xxxxxxxxxx/xxxxxxxxxx.key  --enable-https
```

**Comment by bhzhu203** [comment]
nodejs program works perfectly. 

[2022-06-16T01:22:44.711] [INFO] default - Piping Server 1.12.3
[2022-06-16T01:22:44.738] [INFO] default - Certificate loaded
[2022-06-16T01:22:44.742] [INFO] default - Listen HTTP on 8887...
[2022-06-16T01:22:44.742] [INFO] default - Listen HTTPS on 8888...

**Comment by nwtgck** [comment]
Thanks for the report. I should bery zerossl.

**Comment by nwtgck** [comment]
This is a report of my progress. I tried ZeroSSL and reproduced the error.

**Comment by nwtgck** [comment]
I fixed in https://github.com/nwtgck/piping-server-rust/commit/ae57f2f2997f3e7a20fa25163cc2325f5abbcea9. I will release.

**Comment by nwtgck** [comment]
Now you can use 0.14.0.

```bash
curl -L https://github.com/nwtgck/piping-server-rust/releases/download/v0.14.0/piping-server-x86_64-unknown-linux-musl.tar.gz | tar xzf -
```

**Comment by bhzhu203** [comment]
@nwtgck Great !  The issue is be sloved. I use the version fb1feb97ff33ee9c297eaf5bd01ce3f6583406c4 which has no problem :)
